---
kind: pipeline
type: docker
name: default

services:
  - name: database-drone
    image: 'postgres:10.7'
    environment:
      POSTGRES_USER: integration
      POSTGRES_DB: postgres

steps:
  - name: npm-login
    image: node:gallium-buster
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
  - name: bootstrap
    image: node:gallium-buster
    commands:
      - npm ci
      - npm run build
  - name: unit-test
    group: test
    image: node:gallium-buster
    commands:
      - npm test
  - name: integration-test
    group: test
    image: node:gallium-buster
    commands:
      - npm run test:int
  - name: publish
    image: node:gallium-buster
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    when:
      branch:
      - master
      event:
      - push
    commands:
      - npm whoami
      - npm run build
      - npm run documentation
      - npm run release
